# This workflow will do a clean install of node dependencies and build the package 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, '[0-9]+.[0-9]+.x' ]
  pull_request:
    branches: [ master, '[0-9]+.[0-9]+.x' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build
